services:

  postgres:
    image: postgres:14-alpine
    environment:
      # POSTGRES_DB: coffeeshop
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    networks:
      - coffeeshop-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      # RABBITMQ_DEFAULT_USER: user
      # RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coffeeshop-network
    healthcheck:
      # test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      test: rabbitmq-diagnostics -q ping
    depends_on:
      postgres:
        condition: service_healthy

  product:
    image: khanhd6/go-coffeeshop-product:latest
    environment:
      APP_NAME: "product-service in docker"
      # PG_URL: postgres://user:password@postgres:5432/coffeeshop?sslmode=disable
      # PG_DSN_URL: host=postgres user=user password=password dbname=coffeeshop sslmode=disable
      # PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      # PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      # RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - coffeeshop-network

  counter:
    image: khanhd6/go-coffeeshop-counter:latest
    environment:
      APP_NAME: "counter-service in docker"
      IN_DOCKER: "true"
      # PG_URL: postgres://user:password@postgres:5432/coffeeshop?sslmode=disable
      # PG_DSN_URL: host=postgres user=user password=password dbname=coffeeshop sslmode=disable
      # RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PRODUCT_CLIENT_URL: product:5001
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - coffeeshop-network

  proxy:
    image: khanhd6/go-coffeeshop-proxy:latest
    environment:
      APP_NAME: "proxy-service in docker"
      GRPC_PRODUCT_HOST: "product"
      GRPC_PRODUCT_PORT: 5001
      GRPC_COUNTER_HOST: "counter"
      GRPC_COUNTER_PORT: 5002
    ports:
      - "5000:5000"
    depends_on:
      - product
      - counter
    networks:
      - coffeeshop-network

  web:
    image: khanhd6/go-coffeeshop-web:latest
    environment:
      REVERSE_PROXY_URL: http://localhost:5000
      WEB_PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      - proxy
    networks:
      - coffeeshop-network

  barista:
    image: khanhd6/go-coffeeshop-barista:latest
    environment:
      APP_NAME: "barista-service in docker"
      IN_DOCKER: "true"
      # PG_URL: postgres://user:password@postgres:5432/coffeeshop?sslmode=disable
      # PG_DSN_URL: host=postgres user=user password=password dbname=coffeeshop sslmode=disable
      # RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - coffeeshop-network

  kitchen:
    image: khanhd6/go-coffeeshop-kitchen:latest
    environment:
      APP_NAME: "kitchen-service in docker"
      IN_DOCKER: "true"
      # PG_URL: postgres://user:password@postgres:5432/coffeeshop?sslmode=disable
      # PG_DSN_URL: host=postgres user=user password=password dbname=coffeeshop sslmode=disable
      # RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - coffeeshop-network

networks:
  coffeeshop-network:

volumes:
  pgdata: